// This file will be generated by Supabase CLI typically
// For now, we'll create a basic type structure

export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          role: string;
          profile_data: any;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          email: string;
          role: string;
          profile_data?: any;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          role?: string;
          profile_data?: any;
          created_at?: string;
          updated_at?: string;
        };
      };
      attachments: {
        Row: {
          id: string;
          entity_type: string;
          entity_id: string;
          file_name: string;
          file_path: string;
          file_size: number;
          mime_type: string;
          metadata: any;
          uploaded_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          entity_type: string;
          entity_id: string;
          file_name: string;
          file_path: string;
          file_size: number;
          mime_type: string;
          metadata?: any;
          uploaded_by: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          entity_type?: string;
          entity_id?: string;
          file_name?: string;
          file_path?: string;
          file_size?: number;
          mime_type?: string;
          metadata?: any;
          uploaded_by?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
  };
};
